### ISSUE TITLE
Error: Execution of identify command failed

### ISSUE THREAD

**Issue by ZackMercury** [krzysztof-o/spritesheet.js#87]
```
D:\Media\Games\DigimonBattle\GUI\loading_eq>identify
Version: ImageMagick 7.1.0-57 Q16 x64 eadf378:20221230 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC OpenCL
Delegates (built-in): bzlib cairo freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raqm raw rsvg tiff webp xml zip zlib
Compiler: Visual Studio 2022 (193431937)
Usage: identify [options ...] file [ [options ...] file ... ]

Image Settings:
  -alpha option        on, activate, off, deactivate, set, opaque, copy
                       transparent, extract, background, or shape
  -antialias           remove pixel-aliasing
  -authenticate password
                       decipher image with this password
  -clip                clip along the first path from the 8BIM profile
  -clip-mask filename  associate a clip mask with the image
  -clip-path id        clip along a named path from the 8BIM profile
  -colorspace type     alternate image colorspace
  -crop geometry       cut out a rectangular region of the image
  -define format:option
                       define one or more image format options
  -density geometry    horizontal and vertical density of the image
  -depth value         image depth
  -endian type         endianness (MSB or LSB) of the image
  -extract geometry    extract area from image
  -features distance   analyze image features (e.g. contrast, correlation)
  -format "string"     output formatted image characteristics
  -fuzz distance       colors within this distance are considered equal
  -gamma value         of gamma correction
  -interlace type      type of image interlacing scheme
  -interpolate method  pixel color interpolation method
  -limit type value    pixel cache resource limit
  -matte               store matte channel if the image has one
  -moments             report image moments
  -monitor             monitor progress
  -ping                efficiently determine image attributes
  -precision value     maximum number of significant digits to print
  -quiet               suppress all warning messages
  -regard-warnings     pay attention to warning messages
  -respect-parentheses settings remain in effect until parenthesis boundary
  -sampling-factor geometry
                       horizontal and vertical sampling factor
  -seed value          seed a new sequence of pseudo-random numbers
  -set attribute value set an image attribute
  -size geometry       width and height of image
  -strip               strip image of all profiles and comments
  -unique              display the number of unique colors in the image
  -units type          the units of image resolution
  -verbose             print detailed information about the image
  -virtual-pixel method
                       virtual pixel access method

Image Operators:
  -auto-orient         automagically orient (rotate) image
  -channel mask        set the image channel mask
  -grayscale method    convert image to grayscale
  -negate              replace every pixel with its complementary color

Miscellaneous Options:
  -debug events        display copious debugging information
  -help                print program options
  -list type           print a list of supported option arguments
  -log format          format of debugging information
  -version             print version information

By default, the image format of 'file' is determined by its magic
number.  To specify a particular image format, precede the filename
with an image format name and a colon (i.e. ps:image) or specify the
image type as the filename suffix (i.e. image.ps).  Specify 'file' as
'-' for standard input or output.

D:\Media\Games\DigimonBattle\GUI\loading_eq>spritesheet-js ./*.png --powerOfTwo --padding 0 -f pixi.js -n loading
C:\Users\dioro\AppData\Roaming\nvm\v22.2.0\node_modules\spritesheet-js\index.js:129
    if (err) throw err;
             ^

Error: Execution of identify command failed. Ensure that ImageMagick Legacy Tools are installed and added to your PATH.
    at C:\Users\dioro\AppData\Roaming\nvm\v22.2.0\node_modules\spritesheet-js\lib\generator.js:52:28
    at ChildProcess.<anonymous> (C:\Users\dioro\AppData\Roaming\nvm\v22.2.0\node_modules\spritesheet-js\node_modules\platform-command\platforms\windows\command.js:12:4)
    at ChildProcess.emit (node:events:520:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:520:28)
    at Pipe.<anonymous> (node:net:338:12)
```

**Comment by ZackMercury** [comment]
UPD, after checking the [previous issue](https://github.com/krzysztof-o/spritesheet.js/issues/86), that was not a nice way to find out that this tool is incompatible with Windows due to some bash spawning magic.
Successfully runs in WSL, thanks for warning in your readme and saving my time

![image](https://github.com/user-attachments/assets/a13b6810-efa6-49cf-927d-f74df76ce9de)
